INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '14:00:00', '2023-07-10', 'Stadium A', 'Note: Match postponed to later date');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '16:30:00', '2023-07-12', 'Stadium B', 'Note: No spectators allowed');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '10:00:00', '2023-07-15', 'Stadium C', 'Note: Match rescheduled due to weather conditions');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '19:45:00', '2023-07-18', 'Stadium D', 'Note: VIP guests in attendance');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '14:30:00', '2023-07-20', 'Stadium E', 'Note: Match to be broadcasted live');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '17:15:00', '2023-07-23', 'Stadium F', 'Note: Limited parking available');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (1, '20:00:00', '2023-07-25', 'Stadium G', 'Note: Match expected to be highly competitive');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (2, '11:30:00', '2023-07-28', 'Stadium H', 'Note: Match to be played on artificial turf');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (2, '15:45:00', '2023-07-31', 'Stadium I', 'Note: Match in support of charity');
INSERT INTO matches (tournament_id, start_time, start_date, location, notes) VALUES (2, '18:30:00', '2023-08-03', 'Stadium J', 'Note: Tickets sold out');