DROP TABLE IF EXISTS players CASCADE;

CREATE TABLE players (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  match_id INTEGER REFERENCES matches(id) ON DELETE CASCADE NOT NULL,
  player_name VARCHAR(50),
  score VARCHAR(50)
);